### PR TITLE
Worldguard 6 compatibility

### PR DESCRIPTION
**Pull request by sebastianbinder**
please send feedback if you'd like to have any changes.

### CODE REVIEW

**Comment by sebastianbinder** [comment]
Any plans for merging this? …

**Comment by sebastianbinder** [comment]
@Postremus ?

**Comment by sebastianbinder** [comment]
Bump...

**Comment by sebastianbinder** [comment]
@Postremus ?

**Comment by Postremus** [comment]
Will not be merged. Current plan is to remove the worldguard dependency completly, and rock on with our own, as minimalistic as possible implementation for regions.

**Pull request closed without merging**
